"""SQLAlchemy declarative base, naming convention, shared mixins.

Phase 3 implementation of docs/database_design_v1.2.md section 0 (设计总则).
- All tables: id BIGINT GENERATED BY DEFAULT AS IDENTITY (0.2, no UUID).
- All FKs RESTRICT (no CASCADE) — every ForeignKey uses ondelete="RESTRICT".
- A-class template (0.8): created_by/created_at/updated_by/updated_at/version.
- B/D-class template (0.8): occurred_at NOT NULL, recorded_at NOT NULL DEFAULT now(),
  created_by.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Identity, MetaData, func, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    # %(constraint_name)s-only template: explicit CHECK names pass through unchanged
    # (a token-bearing template would re-wrap already-qualified explicit names).
    "ck": "%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    metadata = metadata


class TableBase(Base):
    """Common columns for every physical table (design 0.2). __abstract__: id-only declarative base."""

    __abstract__ = True

    id: Mapped[int] = mapped_column(
        BigInteger, Identity(always=False), primary_key=True, autoincrement=True
    )


class ALifecycleMixin:
    """A-class current-value tables (design 0.8 / 18 章)."""

    created_by: Mapped[int | None] = mapped_column(BigInteger)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    updated_by: Mapped[int | None] = mapped_column(BigInteger)
    updated_at: Mapped[datetime | None] = mapped_column(DateTime)
    version: Mapped[int] = mapped_column(default=1, server_default=text("1"), nullable=False)


class AMasterDataMixin(ALifecycleMixin):
    """A-class master data tables with soft-delete flag (design 0.4/0.8)."""

    is_active: Mapped[bool] = mapped_column(default=True, server_default=text("true"), nullable=False)


class BFactMixin:
    """B/D-class append-only fact/event tables (design 0.8)."""

    occurred_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    created_by: Mapped[int | None] = mapped_column(BigInteger)
