"""labor_business_round2

Revision ID: beb27ec57bc8
Revises: f0a1b2c3d4e5
Create Date: 2026-09-20 11:23:14.792242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb27ec57bc8'
down_revision: Union[str, Sequence[str], None] = 'f0a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_occupation_dict',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_no', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_occupation_dict')),
    sa.UniqueConstraint('code', name=op.f('uq_employee_occupation_dict_code')),
    schema='ref'
    )
    # 初始职业/岗位字典（设计审查报告 C.2 初始值；幂等，重复升级安全）。
    op.execute(
        "INSERT INTO ref.employee_occupation_dict(code, name, sort_no, is_active) VALUES "
        "('welder','电焊工',1,true),('fitter','装配工',2,true),"
        "('grinder','打磨工',3,true),('rigger','起重工',4,true) "
        "ON CONFLICT (code) DO NOTHING"
    )
    op.create_table('component_type_process_template',
    sa.Column('component_type_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['component_type_id'], ['ref.component_type_dict.id'], name=op.f('fk_component_type_process_template_component_type_id_component_type_dict'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component_type_process_template')),
    sa.UniqueConstraint('component_type_id', 'version_no', name='uq_ctpt_component_type_version'),
    schema='eng'
    )
    op.create_index('ix_ctpt_current', 'component_type_process_template', ['component_type_id'], unique=True, schema='eng', postgresql_where=sa.text('is_current'))
    op.create_check_constraint('ck_ctpt_status_values', 'component_type_process_template', sa.text("status IN ('active','deprecated')"), schema='eng')
    op.create_table('employee_occupation',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('occupation_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['md.employee.id'], name=op.f('fk_employee_occupation_employee_id_employee'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['occupation_id'], ['ref.employee_occupation_dict.id'], name=op.f('fk_employee_occupation_occupation_id_employee_occupation_dict'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_occupation')),
    sa.UniqueConstraint('employee_id', 'occupation_id', name='uq_employee_occupation_emp_occ'),
    schema='md'
    )
    op.create_index('ix_employee_occupation_occupation_id', 'employee_occupation', ['occupation_id'], unique=False, schema='md')
    op.create_table('team_operation_capability',
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_type_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['operation_type_id'], ['ref.operation_type.id'], name=op.f('fk_team_operation_capability_operation_type_id_operation_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['md.team.id'], name=op.f('fk_team_operation_capability_team_id_team'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_operation_capability')),
    sa.UniqueConstraint('team_id', 'operation_type_id', name='uq_team_operation_capability_team_op'),
    schema='md'
    )
    op.create_index('ix_team_operation_capability_operation_type_id', 'team_operation_capability', ['operation_type_id'], unique=False, schema='md')
    op.create_table('component_type_process_step',
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('operation_type_id', sa.BigInteger(), nullable=True),
    sa.Column('project_operation_id', sa.BigInteger(), nullable=True),
    sa.Column('default_requirement', sa.String(length=255), nullable=True),
    sa.Column('step_status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("step_status IN ('active','deprecated')", name=op.f('ck_ctps_step_status_values')),
    sa.CheckConstraint('(operation_type_id IS NOT NULL AND project_operation_id IS NULL) OR (operation_type_id IS NULL AND project_operation_id IS NOT NULL)', name=op.f('ck_ctps_op_xor')),
    sa.ForeignKeyConstraint(['operation_type_id'], ['ref.operation_type.id'], name=op.f('fk_component_type_process_step_operation_type_id_operation_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_operation_id'], ['eng.project_operation.id'], name=op.f('fk_component_type_process_step_project_operation_id_project_operation'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['eng.component_type_process_template.id'], name=op.f('fk_component_type_process_step_template_id_component_type_process_template'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component_type_process_step')),
    sa.UniqueConstraint('template_id', 'step_no', name='uq_ctps_template_step_no'),
    schema='eng'
    )
    op.create_table('labor_pricing_rule',
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('component_type_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_type_id', sa.BigInteger(), nullable=True),
    sa.Column('project_operation_id', sa.BigInteger(), nullable=True),
    sa.Column('applicable_team_id', sa.BigInteger(), nullable=True),
    sa.Column('price_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('(operation_type_id IS NOT NULL AND project_operation_id IS NULL) OR (operation_type_id IS NULL AND project_operation_id IS NOT NULL)', name=op.f('ck_lpr_op_xor')),
    sa.ForeignKeyConstraint(['applicable_team_id'], ['md.team.id'], name=op.f('fk_labor_pricing_rule_applicable_team_id_team'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['component_type_id'], ['ref.component_type_dict.id'], name=op.f('fk_labor_pricing_rule_component_type_id_component_type_dict'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_type_id'], ['ref.operation_type.id'], name=op.f('fk_labor_pricing_rule_operation_type_id_operation_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['price_unit_id'], ['ref.unit_of_measure.id'], name=op.f('fk_labor_pricing_rule_price_unit_id_unit_of_measure'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_operation_id'], ['eng.project_operation.id'], name=op.f('fk_labor_pricing_rule_project_operation_id_project_operation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labor_pricing_rule')),
    sa.UniqueConstraint('rule_code', name=op.f('uq_labor_pricing_rule_rule_code')),
    schema='eng'
    )
    op.create_index('uq_lpr_dim', 'labor_pricing_rule', [sa.literal_column('component_type_id'), sa.literal_column('COALESCE(operation_type_id, project_operation_id)'), sa.literal_column('COALESCE(applicable_team_id, 0)')], unique=True, schema='eng')
    op.create_table('labor_pricing_rule_version',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_lprv_range')),
    sa.ForeignKeyConstraint(['rule_id'], ['eng.labor_pricing_rule.id'], name=op.f('fk_labor_pricing_rule_version_rule_id_labor_pricing_rule'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labor_pricing_rule_version')),
    sa.UniqueConstraint('rule_id', 'version_no', name='uq_lprv_rule_version'),
    schema='eng'
    )
    op.create_index('ix_lprv_current', 'labor_pricing_rule_version', ['rule_id'], unique=True, schema='eng', postgresql_where=sa.text('is_current'))
    op.create_table('labor_pricing_condition',
    sa.Column('rule_version_id', sa.BigInteger(), nullable=False),
    sa.Column('condition_type', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=8), nullable=False),
    sa.Column('value_low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['eng.labor_pricing_rule_version.id'], name=op.f('fk_labor_pricing_condition_rule_version_id_labor_pricing_rule_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['ref.unit_of_measure.id'], name=op.f('fk_labor_pricing_condition_unit_id_unit_of_measure'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labor_pricing_condition')),
    sa.UniqueConstraint('rule_version_id', 'condition_type', name='uq_lpc_version_condition'),
    schema='eng'
    )
    op.add_column('route_template', sa.Column('standard_template_id', sa.BigInteger(), nullable=True), schema='eng')
    op.add_column('route_template', sa.Column('standard_template_version', sa.Integer(), nullable=True), schema='eng')
    op.add_column('route_template', sa.Column('adopted_by', sa.BigInteger(), nullable=True), schema='eng')
    op.add_column('route_template', sa.Column('adopted_at', sa.DateTime(), nullable=True), schema='eng')
    op.create_index('ix_route_template_standard_template_id', 'route_template', ['standard_template_id'], unique=False, schema='eng')
    op.create_foreign_key(op.f('fk_route_template_standard_template_id_component_type_process_template'), 'route_template', 'component_type_process_template', ['standard_template_id'], ['id'], source_schema='eng', referent_schema='eng', ondelete='RESTRICT')
    op.add_column('actual_component', sa.Column('component_type_id', sa.BigInteger(), nullable=True), schema='prod')
    op.create_foreign_key(op.f('fk_actual_component_component_type_id_component_type_dict'), 'actual_component', 'component_type_dict', ['component_type_id'], ['id'], source_schema='prod', referent_schema='ref', ondelete='RESTRICT')
    op.add_column('component_list_item', sa.Column('component_type_id', sa.BigInteger(), nullable=True), schema='prod')
    op.create_foreign_key(op.f('fk_component_list_item_component_type_id_component_type_dict'), 'component_list_item', 'component_type_dict', ['component_type_id'], ['id'], source_schema='prod', referent_schema='ref', ondelete='RESTRICT')
    op.add_column('production_task', sa.Column('rework_order_id', sa.BigInteger(), nullable=True), schema='prod')
    op.create_foreign_key(op.f('fk_production_task_rework_order_id_rework_order'), 'production_task', 'rework_order', ['rework_order_id'], ['id'], source_schema='prod', referent_schema='prod', ondelete='RESTRICT')
    op.add_column('rework_order', sa.Column('chargeability', sa.String(length=16), nullable=True), schema='prod')
    op.create_check_constraint('ck_rework_order_chargeability_values', 'rework_order', sa.text("chargeability IN ('chargeable','non_chargeable')"), schema='prod')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_rework_order_chargeability_values', 'rework_order', schema='prod', type_='check')
    op.drop_column('rework_order', 'chargeability', schema='prod')
    op.drop_constraint(op.f('fk_production_task_rework_order_id_rework_order'), 'production_task', schema='prod', type_='foreignkey')
    op.drop_column('production_task', 'rework_order_id', schema='prod')
    op.drop_constraint(op.f('fk_component_list_item_component_type_id_component_type_dict'), 'component_list_item', schema='prod', type_='foreignkey')
    op.drop_column('component_list_item', 'component_type_id', schema='prod')
    op.drop_constraint(op.f('fk_actual_component_component_type_id_component_type_dict'), 'actual_component', schema='prod', type_='foreignkey')
    op.drop_column('actual_component', 'component_type_id', schema='prod')
    op.drop_constraint(op.f('fk_route_template_standard_template_id_component_type_process_template'), 'route_template', schema='eng', type_='foreignkey')
    op.drop_index('ix_route_template_standard_template_id', table_name='route_template', schema='eng')
    op.drop_column('route_template', 'adopted_at', schema='eng')
    op.drop_column('route_template', 'adopted_by', schema='eng')
    op.drop_column('route_template', 'standard_template_version', schema='eng')
    op.drop_column('route_template', 'standard_template_id', schema='eng')
    op.drop_table('labor_pricing_condition', schema='eng')
    op.drop_index('ix_lprv_current', table_name='labor_pricing_rule_version', schema='eng', postgresql_where=sa.text('is_current'))
    op.drop_table('labor_pricing_rule_version', schema='eng')
    op.drop_index('uq_lpr_dim', table_name='labor_pricing_rule', schema='eng')
    op.drop_table('labor_pricing_rule', schema='eng')
    op.drop_table('component_type_process_step', schema='eng')
    op.drop_index('ix_team_operation_capability_operation_type_id', table_name='team_operation_capability', schema='md')
    op.drop_table('team_operation_capability', schema='md')
    op.drop_index('ix_employee_occupation_occupation_id', table_name='employee_occupation', schema='md')
    op.drop_table('employee_occupation', schema='md')
    op.drop_index('ix_ctpt_current', table_name='component_type_process_template', schema='eng', postgresql_where=sa.text('is_current'))
    op.drop_constraint('ck_ctpt_status_values', 'component_type_process_template', schema='eng', type_='check')
    op.drop_table('component_type_process_template', schema='eng')
    op.drop_table('employee_occupation_dict', schema='ref')
    # ### end Alembic commands ###
