"""Phase 4 M-P4-3：MES 生产成本 / 班组结算口径模型。

依据 M-P4-3 开发任务书：
- 新增 eng.project_operation（项目工序稳定身份，标准/自定义互斥）
- 新增 eng.project_operation_price（不可破坏的历史价格版本）
- eng.route_template_step：operation_type_id 改可空 + 新增 project_operation_id（互斥）
- prod.production_measure.measure_type 增加 hole_count
- 视图 eng.v_operation_cost_trial / eng.v_project_production_cost（时间旅行 + 5 计价 + 异常标记）
- T-17 触发器：价格版本区间不重叠 / 单一当前 / 已生效冻结（不引入 btree_gist，用 advisory 锁 + 部分唯一索引）

Revision ID: f0a1b2c3d4e5
Revises: e9a3b5c7d921
Create Date: 2026-09-19
"""
from alembic import op

revision = "f0a1b2c3d4e5"
down_revision = "e9a3b5c7d921"
branch_labels = None
depends_on = None

UPGRADE_SQL = r"""
-- ============================================================
-- 1. eng.project_operation（A 类主数据）
-- ============================================================
CREATE TABLE eng.project_operation (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    main_project_id        BIGINT REFERENCES md.main_project(id) ON DELETE RESTRICT,
    subproject_id          BIGINT REFERENCES md.subproject(id) ON DELETE RESTRICT,
    project_operation_code VARCHAR(64) NOT NULL,
    operation_type_id      BIGINT REFERENCES ref.operation_type(id) ON DELETE RESTRICT,
    custom_name            VARCHAR(128),
    default_team_id        BIGINT REFERENCES md.team(id) ON DELETE RESTRICT,
    is_active              BOOLEAN NOT NULL DEFAULT true,
    created_by             BIGINT,
    created_at             TIMESTAMP NOT NULL DEFAULT now(),
    updated_by             BIGINT,
    updated_at             TIMESTAMP,
    version                INT NOT NULL DEFAULT 1,
    CONSTRAINT ck_po_identity CHECK (
        (operation_type_id IS NOT NULL AND custom_name IS NULL) OR
        (operation_type_id IS NULL AND custom_name IS NOT NULL)),
    CONSTRAINT ck_po_scope CHECK (main_project_id IS NOT NULL OR subproject_id IS NOT NULL),
    CONSTRAINT uq_po_main_project_code UNIQUE (main_project_id, project_operation_code),
    CONSTRAINT uq_po_subproject_code UNIQUE (subproject_id, project_operation_code)
);

-- ============================================================
-- 2. eng.project_operation_price（B 类历史版本）
-- ============================================================
CREATE TABLE eng.project_operation_price (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_operation_id  BIGINT NOT NULL REFERENCES eng.project_operation(id) ON DELETE RESTRICT,
    version_no            INT NOT NULL,
    price                 NUMERIC(12,2) NOT NULL,
    price_basis           VARCHAR(16) NOT NULL,
    effective_from        DATE NOT NULL,
    effective_to          DATE,
    is_current            BOOLEAN NOT NULL DEFAULT false,
    approved_by           BIGINT,
    occurred_at           TIMESTAMP NOT NULL,
    recorded_at           TIMESTAMP NOT NULL DEFAULT now(),
    created_by            BIGINT,
    CONSTRAINT ck_pop_price_basis CHECK (
        price_basis IN ('weight','piece','length','hour','hole_count')),
    CONSTRAINT ck_pop_range CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT uq_pop_po_version UNIQUE (project_operation_id, version_no)
);
CREATE INDEX ix_pop_lookup ON eng.project_operation_price (project_operation_id, effective_from, effective_to);
-- 单一当前版本（部分唯一索引，无需 btree_gist）
CREATE UNIQUE INDEX uq_pop_current ON eng.project_operation_price (project_operation_id) WHERE is_current;

-- ============================================================
-- 3. eng.route_template_step：operation_type_id 可空 + project_operation_id
-- ============================================================
ALTER TABLE eng.route_template_step ALTER COLUMN operation_type_id DROP NOT NULL;
ALTER TABLE eng.route_template_step ADD COLUMN project_operation_id BIGINT;
ALTER TABLE eng.route_template_step
    ADD CONSTRAINT fk_route_template_step_project_operation
    FOREIGN KEY (project_operation_id) REFERENCES eng.project_operation(id) ON DELETE RESTRICT;
ALTER TABLE eng.route_template_step
    ADD CONSTRAINT ck_rts_op_xor CHECK (
        (operation_type_id IS NOT NULL AND project_operation_id IS NULL) OR
        (operation_type_id IS NULL AND project_operation_id IS NOT NULL));

-- ============================================================
-- 4. prod.production_measure：measure_type 增加 hole_count
-- ============================================================
ALTER TABLE prod.production_measure DROP CONSTRAINT ck_production_measure_type_values;
ALTER TABLE prod.production_measure
    ADD CONSTRAINT ck_production_measure_type_values CHECK (
        measure_type IN ('weight','cut_length','weld_length','mach_length','hours','hole_count'));

-- ============================================================
-- 5. 视图：成本试算明细 + 项目生产成本汇总
--    粒度 = 生产任务（attempt），非报告，避免按报告重复计数；
--    度量跨任务全部报告聚合，发生时间取自报告 MAX(occurred_at)。
-- ============================================================
CREATE VIEW eng.v_operation_cost_trial AS
WITH base AS (
    SELECT
        pt.id              AS task_id,
        pt.execute_team_id,
        (SELECT MAX(pr.occurred_at) FROM prod.production_report pr WHERE pr.task_id = pt.id) AS occurred_at,
        pt.attempt,
        (pt.attempt > 1 OR pt.rework_of_task_id IS NOT NULL) AS is_rework,
        ac.id             AS actual_component_id,
        ac.component_no,
        ac.actual_weight,
        sp.main_project_id,
        sp.id             AS subproject_id,
        rts.id            AS route_template_step_id,
        rts.operation_type_id,
        rts.project_operation_id AS rts_po_id,
        (SELECT COALESCE(SUM(pm.value), 0)
           FROM prod.production_report pr2
           JOIN prod.production_measure pm ON pm.report_id = pr2.id
          WHERE pr2.task_id = pt.id AND pm.measure_type = 'weight') AS w_val,
        (SELECT COALESCE(SUM(pm.value), 0)
           FROM prod.production_report pr2
           JOIN prod.production_measure pm ON pm.report_id = pr2.id
          WHERE pr2.task_id = pt.id AND pm.measure_type IN ('cut_length','weld_length','mach_length')) AS len_val,
        (SELECT COALESCE(SUM(rw.work_hours), 0)
           FROM prod.production_report pr2
           JOIN prod.production_report_worker rw ON rw.report_id = pr2.id
          WHERE pr2.task_id = pt.id) AS hr_worker,
        (SELECT COALESCE(SUM(pm.value), 0)
           FROM prod.production_report pr2
           JOIN prod.production_measure pm ON pm.report_id = pr2.id
          WHERE pr2.task_id = pt.id AND pm.measure_type = 'hours') AS hr_val,
        (SELECT COALESCE(SUM(pm.value), 0)
           FROM prod.production_report pr2
           JOIN prod.production_measure pm ON pm.report_id = pr2.id
          WHERE pr2.task_id = pt.id AND pm.measure_type = 'hole_count') AS hole_val,
        (SELECT CASE WHEN EXISTS (
            SELECT 1 FROM prod.production_report pr2
            JOIN prod.production_measure pm ON pm.report_id = pr2.id
            WHERE pr2.task_id = pt.id AND pm.measure_type = 'weight') THEN 1 ELSE 0 END) AS has_w
    FROM prod.production_task pt
    JOIN eng.route_template_step rts ON rts.id = pt.route_template_step_id
    JOIN prod.actual_component ac    ON ac.id = pt.actual_component_id
    JOIN md.subproject sp            ON sp.id = ac.subproject_id
    WHERE EXISTS (SELECT 1 FROM prod.production_report pr2 WHERE pr2.task_id = pt.id)
),
po_resolved AS (
    SELECT b.*, po.id AS project_operation_id, po.custom_name
    FROM base b
    LEFT JOIN LATERAL (
        SELECT po2.id, po2.custom_name
        FROM eng.project_operation po2
        WHERE po2.is_active
          AND ((b.rts_po_id IS NOT NULL AND po2.id = b.rts_po_id)
            OR (b.rts_po_id IS NULL AND po2.operation_type_id = b.operation_type_id
                AND (po2.main_project_id = b.main_project_id OR po2.subproject_id = b.subproject_id)))
        ORDER BY po2.id
        LIMIT 1
    ) po ON true
),
priced AS (
    SELECT r.*, pop.price_basis, pop.price
    FROM po_resolved r
    LEFT JOIN LATERAL (
        SELECT x.price_basis, x.price
        FROM eng.project_operation_price x
        WHERE x.project_operation_id = r.project_operation_id
          AND x.effective_from <= r.occurred_at::date
          AND (x.effective_to IS NULL OR r.occurred_at::date < x.effective_to)
        ORDER BY x.effective_from DESC
        LIMIT 1
    ) pop ON true
)
SELECT
    task_id,
    actual_component_id,
    component_no,
    main_project_id,
    subproject_id,
    project_operation_id,
    operation_type_id,
    custom_name,
    execute_team_id,
    occurred_at,
    attempt,
    is_rework,
    price_basis,
    price,
    CASE
        WHEN price_basis = 'weight'  THEN CASE WHEN has_w = 1 THEN w_val ELSE actual_weight END
        WHEN price_basis = 'piece'   THEN 1
        WHEN price_basis = 'length'  THEN len_val
        WHEN price_basis = 'hour'    THEN COALESCE(hr_worker, hr_val)
        WHEN price_basis = 'hole_count' THEN hole_val
    END AS measure_value,
    CASE
        WHEN project_operation_id IS NULL OR price IS NULL THEN 'MISSING_PRICE'
        WHEN execute_team_id IS NULL THEN 'MISSING_TEAM'
        WHEN price_basis = 'weight' AND has_w = 0 AND actual_weight IS NULL THEN 'MISSING_MEASURE'
        WHEN price_basis = 'weight' AND has_w = 0 AND actual_weight IS NOT NULL THEN 'MEASURE_FALLBACK'
        WHEN price_basis = 'length'  AND len_val = 0 THEN 'MISSING_MEASURE'
        WHEN price_basis = 'hour'    AND hr_worker = 0 AND hr_val = 0 THEN 'MISSING_MEASURE'
        WHEN price_basis = 'hole_count' AND hole_val = 0 THEN 'MISSING_MEASURE'
        ELSE 'PRECISE'
    END AS anomaly_status,
    CASE
        WHEN price IS NULL THEN NULL
        WHEN price_basis = 'weight'  AND has_w = 0 AND actual_weight IS NULL THEN NULL
        WHEN price_basis = 'length'  AND len_val = 0 THEN NULL
        WHEN price_basis = 'hour'    AND hr_worker = 0 AND hr_val = 0 THEN NULL
        WHEN price_basis = 'hole_count' AND hole_val = 0 THEN NULL
        ELSE (
            CASE
                WHEN price_basis = 'weight'  THEN CASE WHEN has_w = 1 THEN w_val ELSE actual_weight END
                WHEN price_basis = 'piece'   THEN 1
                WHEN price_basis = 'length'  THEN len_val
                WHEN price_basis = 'hour'    THEN COALESCE(hr_worker, hr_val)
                WHEN price_basis = 'hole_count' THEN hole_val
            END
        ) * price
    END AS amount
FROM priced;

CREATE VIEW eng.v_project_production_cost AS
SELECT
    main_project_id,
    subproject_id,
    project_operation_id,
    execute_team_id,
    date_trunc('month', occurred_at) AS month,
    COUNT(*) FILTER (WHERE NOT is_rework) AS normal_count,
    COUNT(*) FILTER (WHERE is_rework)     AS rework_count,
    SUM(amount) FILTER (WHERE NOT is_rework) AS normal_cost,
    SUM(amount) FILTER (WHERE is_rework)     AS rework_cost,
    SUM(amount) AS total_cost
FROM eng.v_operation_cost_trial
GROUP BY main_project_id, subproject_id, project_operation_id, execute_team_id,
         date_trunc('month', occurred_at);

-- ============================================================
-- 6. T-17 价格版本守卫（不引入 btree_gist）
-- ============================================================
CREATE OR REPLACE FUNCTION mes_t17_price_version_guard() RETURNS trigger AS $$
DECLARE
    v_is_future boolean;
BEGIN
    -- 按 project_operation 串行化（事务级 advisory 锁），避免并发改价产生两个当前版本
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        PERFORM pg_advisory_xact_lock(NEW.project_operation_id);
    END IF;

    IF TG_OP = 'DELETE' THEN
        -- 已生效（effective_from <= 今天）价格版本禁止删除；未来版本可删
        IF OLD.effective_from <= CURRENT_DATE THEN
            RAISE EXCEPTION 'T-17: 已生效价格版本(effective_from=%)禁止删除', OLD.effective_from;
        END IF;
        RETURN OLD;
    END IF;

    -- 生效区间不重叠（NEW 与同 po 其它版本）
    IF EXISTS (
        SELECT 1 FROM eng.project_operation_price x
         WHERE x.project_operation_id = NEW.project_operation_id
           AND x.id <> COALESCE(OLD.id, -1)
           AND x.effective_from < COALESCE(NEW.effective_to, DATE '9999-12-31')
           AND NEW.effective_from < COALESCE(x.effective_to, DATE '9999-12-31')
    ) THEN
        RAISE EXCEPTION 'T-17: 价格版本生效区间重叠（project_operation_id=%）', NEW.project_operation_id;
    END IF;

    -- 单一当前版本（关闭其它当前版本）
    IF NEW.is_current THEN
        UPDATE eng.project_operation_price
           SET is_current = false
         WHERE project_operation_id = NEW.project_operation_id
           AND id <> COALESCE(OLD.id, -1)
           AND is_current;
    END IF;

    -- 未来版本（effective_from > 今天）：自由编辑/删除
    v_is_future := (NEW.effective_from > CURRENT_DATE);
    IF v_is_future THEN
        RETURN NEW;
    END IF;

    -- 已生效（effective_from <= 今天）
    IF TG_OP = 'UPDATE' THEN
        IF OLD.is_current = false THEN
            -- 已关闭历史版本：完全冻结（回放用，改价=关旧+开新）
            RAISE EXCEPTION 'T-17: 已生效历史价格版本禁止修改（回放用；改价=关旧版本+新建版本）';
        END IF;
        -- 当前开放版本：仅允许关闭（effective_to / is_current），不得直接改价格/区间
        IF (NEW.price IS DISTINCT FROM OLD.price)
           OR (NEW.price_basis IS DISTINCT FROM OLD.price_basis)
           OR (NEW.effective_from IS DISTINCT FROM OLD.effective_from)
           OR (NEW.version_no IS DISTINCT FROM OLD.version_no)
           OR (NEW.project_operation_id IS DISTINCT FROM OLD.project_operation_id)
           OR (NEW.approved_by IS DISTINCT FROM OLD.approved_by) THEN
            RAISE EXCEPTION 'T-17: 当前生效版本仅允许关闭（effective_to/is_current），不得直接修改价格/区间';
        END IF;
        RETURN NEW;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_t17_price_version_guard
    BEFORE INSERT OR UPDATE OR DELETE ON eng.project_operation_price
    FOR EACH ROW EXECUTE FUNCTION mes_t17_price_version_guard();
"""

DOWNGRADE_SQL = r"""
DROP TRIGGER IF EXISTS trg_t17_price_version_guard ON eng.project_operation_price;
DROP FUNCTION IF EXISTS mes_t17_price_version_guard();

DROP VIEW IF EXISTS eng.v_project_production_cost;
DROP VIEW IF EXISTS eng.v_operation_cost_trial;

ALTER TABLE prod.production_measure DROP CONSTRAINT ck_production_measure_type_values;
ALTER TABLE prod.production_measure
    ADD CONSTRAINT ck_production_measure_type_values CHECK (
        measure_type IN ('weight','cut_length','weld_length','mach_length','hours'));

ALTER TABLE eng.route_template_step DROP CONSTRAINT ck_rts_op_xor;
ALTER TABLE eng.route_template_step DROP CONSTRAINT fk_route_template_step_project_operation;
ALTER TABLE eng.route_template_step DROP COLUMN project_operation_id;
ALTER TABLE eng.route_template_step ALTER COLUMN operation_type_id SET NOT NULL;

DROP INDEX IF EXISTS eng.uq_pop_current;
DROP TABLE IF EXISTS eng.project_operation_price;
DROP TABLE IF EXISTS eng.project_operation;
"""


def upgrade() -> None:
    op.execute(UPGRADE_SQL)


def downgrade() -> None:
    op.execute(DOWNGRADE_SQL)
